#!/usr/bin/env python

from gi.repository import Gtk, Gdk
from timetag.capture_pipeline import CapturePipeline
from timetag.hist_plot import HistPlot

Gdk.threads_init()
pipeline = CapturePipeline()
hp = HistPlot(pipeline)
Gtk.main()
