#!/usr/bin/env python

import gi
gi.require_version('Gtk','3.0')
from gi.repository import Gtk, Gdk
from timetag.capture_pipeline import CapturePipeline
from timetag.fret_hist_plot import FretHistPlot

Gdk.threads_init()
pipeline = CapturePipeline()
hp = FretHistPlot(pipeline)
Gtk.main()
