#!/usr/bin/env python

import gi
gi.require_version('Gtk','3.0')
from gi.repository import Gtk, Gdk
from timetag.capture_pipeline import CapturePipeline
from timetag.bin_series_plot import BinSeriesPlot

Gdk.threads_init()
pipeline = CapturePipeline()
hp = BinSeriesPlot(pipeline)
Gtk.main()
